    # How to import numpy

In [1]:
    import numpy as np

    # How to check the version of the numpy package

In [2]:
    print('numpy:', np.__version__)

numpy: 1.23.0


    # Checking the available methods

In [3]:
    print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [4]:
# Creating python List
python_list = [1,2,3,4,5]

In [5]:
# Checking data types
print('Type:', type (python_list))

Type: <class 'list'>


In [6]:
print(python_list)

[1, 2, 3, 4, 5]


In [7]:
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]

In [8]:
 print(two_dimensional_list)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [9]:
 # Creating Numpy(Numerical Python) array from python list

numpy_array_from_list = np.array(python_list)
print(type (numpy_array_from_list))   # <class 'numpy.ndarray'>
print(numpy_array_from_list) # array([1, 2, 3, 4, 5])

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [11]:
# Python list
python_list = [1,2,3,4,5]

numy_array_from_list2 = np.array(python_list, dtype=float)
print(numy_array_from_list2) # array([1., 2., 3., 4., 5.])

[1. 2. 3. 4. 5.]


In [12]:
    numpy_bool_array = np.array([0, 1, -1, 0, 0], dtype=bool)
    print(numpy_bool_array) # array([False,  True,  True, False, False])

[False  True  True False False]


In [13]:
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type (numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
# We can always convert an array back to a python list using tolist().
np_to_list = numpy_array_from_list.tolist()
print(type (np_to_list))
print('one dimensional array:', np_to_list)
print('two dimensional array: ', numpy_two_dimensional_list.tolist())

<class 'list'>
one dimensional array: [1, 2, 3, 4, 5]
two dimensional array:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [15]:
# Numpy array from tuple
# Creating tuple in Python
python_tuple = (1,2,3,4,5)
print(type (python_tuple)) # <class 'tuple'>
print('python_tuple: ', python_tuple) # python_tuple:  (1, 2, 3, 4, 5)

numpy_array_from_tuple = np.array(python_tuple)
print(type (numpy_array_from_tuple)) # <class 'numpy.ndarray'>
print('numpy_array_from_tuple: ', numpy_array_from_tuple) # numpy_array_from_tuple:  [1 2 3 4 5]

<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


In [16]:
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print('shape of nums: ', nums.shape)
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[0, 1, 2, 3],
    [4,5,6,7],
    [8,9,10, 11]])
print(three_by_four_array.shape)

[1 2 3 4 5]
shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)
(3, 4)


In [17]:
int_lists = [-3, -2, -1, 0, 1, 2,3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

[-3 -2 -1  0  1  2  3]
int32
[-3. -2. -1.  0.  1.  2.  3.]
float64


In [18]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                              [3, 4, 5],
                              [6, 7, 8]])

print('The size:', numpy_array_from_list.size) # 5
print('The size:', two_dimensional_list.size)  # 3

The size: 5
The size: 9


In [19]:
# Mathematical Operation
# Addition
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_plus_original = numpy_array_from_list  + 10
print(ten_plus_original)

original array:  [1 2 3 4 5]
[11 12 13 14 15]


In [20]:
# Multiplication
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list * 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[10 20 30 40 50]


In [21]:
# Division
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list / 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


In [22]:
# Modulus; Finding the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list % 3
print(ten_times_original)

original array:  [1 2 3 4 5]
[1 2 0 1 2]


In [23]:
# Floor division: the division result without the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list // 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0 0 0 0 0]


In [24]:
# Exponential is finding some number the power of another:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list  ** 2
print(ten_times_original)

original array:  [1 2 3 4 5]
[ 1  4  9 16 25]


In [25]:
#Int,  Float numbers
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int32
float64
bool


In [26]:
numpy_int_arr = np.array([1,2,3,4], dtype = 'float')
numpy_int_arr

array([1., 2., 3., 4.])

In [27]:
numpy_int_arr = np.array([1., 2., 3., 4.], dtype = 'int')
numpy_int_arr

array([1, 2, 3, 4])

In [28]:
np.array([-3, -2, 0, 1,2,3], dtype='bool')

array([ True,  True, False,  True,  True,  True])

In [30]:
numpy_float_arr.astype('int').astype('str')

array(['1', '2', '3'], dtype='<U11')

In [31]:
# 2 Dimension Array
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(type (two_dimension_array))
print(two_dimension_array)
print('Shape: ', two_dimension_array.shape)
print('Size:', two_dimension_array.size)
print('Data type:', two_dimension_array.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Size: 9
Data type: int32


In [32]:
# 2 Dimension Array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)

First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]


In [33]:
first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print(two_dimension_array)

First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_two_rows_and_columns = two_dimension_array[0:2, 0:2]
print(first_two_rows_and_columns)

[[1 2]
 [4 5]]


In [35]:
two_dimension_array[::]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
two_dimension_array[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [37]:
print(two_dimension_array)
two_dimension_array[1,1] = 55
two_dimension_array[1,2] =44
print(two_dimension_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]


In [38]:
# Numpy Zeroes
# numpy.zeros(shape, dtype=float, order='C')
numpy_zeroes = np.zeros((3,3),dtype=int,order='C')
numpy_zeroes

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
# Numpy Zeroes
numpy_ones = np.ones((3,3),dtype=int,order='C')
print(numpy_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [41]:
twoes = numpy_ones * 2
twoes

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [42]:
# Reshape
# numpy.reshape(), numpy.flatten()
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [43]:
flattened = reshaped.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

In [44]:
    ## Horitzontal Stack
    np_list_one = np.array([1,2,3])
    np_list_two = np.array([4,5,6])

    print(np_list_one + np_list_two)

    print('Horizontal Append:', np.hstack((np_list_one, np_list_two)))

[5 7 9]
Horizontal Append: [1 2 3 4 5 6]


In [45]:
    ## Vertical Stack
    print('Vertical Append:', np.vstack((np_list_one, np_list_two)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [46]:
# Generate a random float  number
random_float = np.random.random()
random_float

0.02242126298622693

In [47]:
# Generate a random float  number
random_floats = np.random.random(5)
random_floats

array([0.41873345, 0.73209817, 0.98649223, 0.08529086, 0.55262185])

In [48]:
# Generating a random integers between 0 and 10

random_int = np.random.randint(0, 11)
random_int

9

In [49]:
# Generating a random integers between 2 and 11, and creating a one row array
random_int = np.random.randint(2,10, size=4)
random_int

array([3, 2, 8, 5])

In [50]:
# Generating a random integers between 0 and 10
random_int = np.random.randint(2,10, size=(3,3))
random_int

array([[8, 6, 2],
       [2, 7, 7],
       [6, 8, 8]])

In [51]:
# np.random.normal(mu, sigma, size)
normal_array = np.random.normal(79, 15, 80)
normal_array

array([ 59.12687012,  84.81703366,  89.87355991,  83.42664852,
        93.96590913,  92.28901095,  75.96468843,  67.49149275,
        67.68233854,  83.66255996,  85.80780914,  36.60941146,
        61.95109526,  69.08973985,  88.74198456,  88.76745273,
       111.57684266,  81.11231988,  92.38599114,  84.77219526,
        95.9883947 ,  82.53491969,  87.8415136 ,  69.68379255,
        91.64671502,  81.15254976,  46.89057045,  54.71672723,
        99.71394912,  85.84685754, 100.00965294,  71.97124392,
        77.41294955,  79.39263647,  72.3807929 ,  95.74783629,
       103.05234764,  78.94520932,  93.05878118,  75.14885946,
        94.59993851,  85.98508446,  92.7837315 ,  63.71421092,
        80.50924082,  93.16092686,  78.28871254,  72.6938794 ,
        85.62086606,  72.45281328, 112.87128783,  67.25305125,
        73.5313111 ,  92.79814603,  57.73215838,  92.46736291,
        70.02899706,  61.95113957,  70.91098359,  77.55343903,
        85.68441378,  92.14468191, 114.37422778,  76.89

In [53]:
four_by_four_matrix = np.matrix(np.ones((4,4), dtype=float))
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [54]:
np.asarray(four_by_four_matrix)[2] = 2
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [1., 1., 1., 1.]])

In [55]:
# creating list using range(starting, stop, step)
lst = range(0, 11, 2)
lst

range(0, 11, 2)

In [56]:
for l in lst:
    print(l)

0
2
4
6
8
10


In [57]:
# Similar to range arange numpy.arange(start, stop, step)
whole_numbers = np.arange(0, 20, 1)
whole_numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [58]:
natural_numbers = np.arange(1, 20, 1)
natural_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [59]:
odd_numbers = np.arange(1, 20, 2)
odd_numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [60]:
even_numbers = np.arange(2, 20, 2)
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
# numpy.linspace()
# numpy.logspace() in Python with Example
# For instance, it can be used to create 10 values from 1 to 5 evenly spaced.
np.linspace(1.0, 5.0, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [62]:
# not to include the last value in the interval
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [63]:
# LogSpace
# LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as np.linspace.

# Syntax:

# numpy.logspace(start, stop, num, endpoint)

np.logspace(2, 4.0, num=4)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [65]:
# to check the size of an array
x = np.array([1,2,3], dtype=np.complex128)
x

array([1.+0.j, 2.+0.j, 3.+0.j])

In [66]:
x.itemsize

16

In [67]:
# indexing and Slicing NumPy Arrays in Python
np_list = np.array([(1,2,3), (4,5,6)])
np_list


array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
print('First row: ', np_list[0])
print('Second row: ', np_list[1])


First row:  [1 2 3]
Second row:  [4 5 6]


In [69]:
print('First column: ', np_list[:,0])
print('Second column: ', np_list[:,1])
print('Third column: ', np_list[:,2])

First column:  [1 4]
Second column:  [2 5]
Third column:  [3 6]


In [70]:
np_normal_dis = np.random.normal(5, 0.5, 100)
np_normal_dis
## min, max, mean, median, sd
print('min: ', two_dimension_array.min())
print('max: ', two_dimension_array.max())
print('mean: ',two_dimension_array.mean())
# print('median: ', two_dimension_array.median())
print('sd: ', two_dimension_array.std())

min:  1
max:  55
mean:  14.777777777777779
sd:  18.913709183069525


In [71]:
print(two_dimension_array)
print('Column with minimum: ', np.amin(two_dimension_array,axis=0))
print('Column with maximum: ', np.amax(two_dimension_array,axis=0))
print('=== Row ==')
print('Row with minimum: ', np.amin(two_dimension_array,axis=1))
print('Row with maximum: ', np.amax(two_dimension_array,axis=1))

[[ 1  2  3]
 [ 4 55 44]
 [ 7  8  9]]
Column with minimum:  [1 2 3]
Column with maximum:  [ 7 55 44]
=== Row ==
Row with minimum:  [1 4 7]
Row with maximum:  [ 3 55  9]


In [72]:
a = [1,2,3]

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 2))


Tile:    [1 2 3 1 2 3]
Repeat:  [1 1 2 2 3 3]


In [73]:
# One random number between [0,1)
one_random_num = np.random.random()
one_random_in = np.random
print(one_random_num)

0.43505288478091675


In [74]:
# Random numbers between [0,1) of shape 2,3
r = np.random.random(size=[2,3])
print(r)

[[0.60516149 0.08778336 0.03310137]
 [0.81148944 0.8637088  0.31847646]]


In [75]:
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))

['a' 'o' 'o' 'u' 'o' 'u' 'a' 'i' 'o' 'i']


In [76]:
## Random numbers between [0, 1] of shape 2, 2
rand = np.random.rand(2,2)
rand

array([[0.10341099, 0.45603746],
       [0.76766589, 0.05492883]])

In [77]:
rand2 = np.random.randn(2,2)
rand2

array([[-0.32939988,  1.22868308],
       [-1.64900217, -1.08415654]])

In [78]:
# Random integers between [0, 10) of shape 2,5
rand_int = np.random.randint(0, 10, size=[5,3])
rand_int

array([[3, 0, 0],
       [2, 7, 0],
       [4, 0, 6],
       [4, 2, 8],
       [9, 8, 9]])

In [80]:
from scipy import stats
np_normal_dis = np.random.normal(5, 0.5, 1000) # mean, standard deviation, number of samples
np_normal_dis
## min, max, mean, median, sd
print('min: ', np.min(np_normal_dis))
print('max: ', np.max(np_normal_dis))
print('mean: ', np.mean(np_normal_dis))
print('median: ', np.median(np_normal_dis))
print('mode: ', stats.mode(np_normal_dis))
print('sd: ', np.std(np_normal_dis))

min:  3.238632908220893
max:  6.397399778657363
mean:  4.97829617695254
median:  4.994269957691854
mode:  ModeResult(mode=array([3.23863291]), count=array([1]))
sd:  0.49027302540021006


C:\Users\david\AppData\Local\Temp\ipykernel_7540\1402113311.py:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print('mode: ', stats.mode(np_normal_dis))


In [81]:
# numpy.dot(): Dot Product in Python using Numpy
# Dot Product
# Numpy is powerful library for matrices computation. For instance, you can compute the dot product with np.dot

# Syntax

# numpy.dot(x, y, out=None)

In [82]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2,3])
g = np.array([4,5,3])
### 1*4+2*5 + 3*6
np.dot(f, g)  # 23

23

In [83]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]]
i = [[5,6],[7,8]]
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])